Add retry logic for sending chat messages.
Fixes bug where errors like the following appear in the log:

08:49:11,274 ERROR Room:253 - Couldn't execute task
java.util.concurrent.CompletionException: org.sobotics.chatexchange.chat.ChatOperationException: The chat operation failed with the message: You can perform this action again in 1 second.
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1702)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.sobotics.chatexchange.chat.ChatOperationException: The chat operation failed with the message: You can perform this action again in 1 second.
        at org.sobotics.chatexchange.chat.Room.post(Room.java:155)
        at org.sobotics.chatexchange.chat.Room.post(Room.java:132)
        at org.sobotics.chatexchange.chat.Room.lambda$send$11(Room.java:276)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
        ... 6 more